//	Full error

int bot(int grid[6][7], int move)
{
    int i,j,k,l;
    for(i=1;i<7;i++)
    {
        for(j=1;j<8;j++)
        {
            if(grid[i][j]==-1)
            break;
        }
    }
    if(i==6)
    {
        if(grid[i-1][j]==0)
        {
            grid[i-1][j]=1;
            move=1;
        }
        else if(grid[i-1][j]==-1)
        {
            if(grid[i-2][j]==0)
            {
                grid[i-2][j]=1;
                move=1;
            }
            else
            {
                if(grid[i-2][j]==-1)
                {
                    if(grid[i-3][j]==0)
                    {
                        grid[i-3[j]=1;
                        move=1;
                    }
                }
            }
        }
        if(grid[i][j+1]==0)
        {
            grid[i][j+1]=1;
            move=1;
        }
        else if(grid[i][j+1]==-1)
        {

            if(grid[i][j+2]==0)
            {
                grid[i][j+2]=1;
                move=1;
            }
            else
            {
                if(grid[i][j+2]==-1)
                {
                    if(grid[i][j+3]==0)
                    {
                        grid[i][j+3]=1;
                        move=1;
                    }
                }
            }
        }
        if(grid[i-1][j+1]==0)
        {
            grid[i-1][j+1]=1;
            move=1;
        }
        else if(grid[i-1][j+1]==-1)
        {
            if(grid[i-2][j+2]==0)
            {
                grid[i-2][j+2]=1;
                move=1;
            }
            else
            {
                if(grid[i-2][j+2]==-1)
                {
                    if(grid[i-3][j+3]==0)
                    {
                        grid[i-3][j+3]=1;
                        move=1;
                    }
                }
            }
        }
    }
    else
    {
        for(k=i;k<7;k++)
        {
            for(l=j;l<8;l++)
            {
                if(grid[k-1][l]==0)
        {
            grid[k-1][l]=1;
            move=1;
        }
        else if(grid[k-1][l]==-1)
        {
            if(grid[k-2][l]==0)
            {
                grid[k-2][l]=1;
                move=1;
            }
            else
            {
                if(grid[k-2][l]==-1)
                {
                    if(grid[k-3][l]==0)
                    {
                        grid[k-3[l]=1;
                        move=1;
                    }
                }
            }
        }
        if(grid[k][l+1]==0)
        {
            grid[k][l+1]=1;
            move=1;
        }
        else if(grid[k][l+1]==-1)
        {

            if(grid[k][l+2]==0)
            {
                grid[k][l+2]=1;
                move=1;
            }
            else
            {
                if(grid[k][l+2]==-1)
                {
                    if(grid[k][l+3]==0)
                    {
                        grid[k][l+3]=1;
                        move=1;
                    }
                }
            }
        }
        if(grid[k-1][l+1]==0)
        {
            grid[k-1][l+1]=1;
            move=1;
        }
        else if(grid[k-1][l+1]==-1)
        {
            if(grid[k-2][l+2]==0)
            {
                grid[k-2][l+2]=1;
                move=1;
            }
            else
            {
                if(grid[k-2][l+2]==-1)
                {
                    if(grid[k-3][l+3]==0)
                    {
                        grid[k-3][l+3]=1;
                        move=1;
                    }
                }
            }
        }
        if(grid[k+1][l+1]==0)
        {
            grid[k+1][l+1]=1;
            move=1;
        }
        else if(grid[k+1][l+1]==-1)
        {
            if(grid[k+2][l+2]==0)
            {
                grid[k+2][l+2]=1;
                move=1;
            }
            else
            {
                if(grid[k+2][l+2]==-1)
                {
                    if(grid[k+3][l+3]==0)
                    {
                        grid[k+3][l+3]=1;
                        move=1;
                    }
                }
            }
        }
        if(grid[k+1][l]==0)
        {
            grid[k+1][l]=1;
            move=1;
        }
        else if(grid[k+1][l]==-1)
        {
            if(grid[k+2][l]==0)
            {
                grid[k+2][l]=1;
                move=1;
            }
            else
            {
                if(grid[k+2][l]==-1)
                {
                    if(grid[k+3][l]==0)
                    {
                        grid[k+3[l]=1;
                        move=1;
                    }
                }
            }
        }

            }
        }
    }
    return move;
}
